# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Plausible Analytics installation tasks
  when: plausible_enabled | bool
  tags:
    - setup-all
    - setup-plausible
    - install-all
    - install-plausible
  block:
    - name: Validate Plausible Analytics configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Plausible Analytics
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Plausible Analytics uninstallation tasks
  when: not plausible_enabled | bool
  tags:
    - setup-all
    - setup-plausible
  block:
    - name: Uninstall Plausible Analytics
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
